# -*- coding: utf-8 -*-
"""Diagnostic remote-control key learner for the future live-channel zapper."""
import time

import xbmcgui

from platformcode import config, logger, platformtools


_CANCEL_ACTIONS = {10, 92}
# Noise generated by Kodi itself while the dialog is open. 203 is
# ACTION_RELOAD_KEYMAPS (triggered after installing our mapping); 100..109 are
# mouse motion/click/drag events and must never become remote bindings.
_IGNORE_ACTIONS = set(range(100, 110)) | {203}


class RemoteKeymapDialog(xbmcgui.WindowXMLDialog):
    def __init__(self, *args, **kwargs):
        super(RemoteKeymapDialog, self).__init__(*args, **kwargs)
        self._phase = 'next'
        self._ready_at = 0
        self._next = None
        self.completed = False

    def onInit(self):
        self._ready_at = time.time() + 0.8
        self._show_prompt()

    def _show_prompt(self, warning=''):
        if self._phase == 'next':
            prompt = 'Premi il tasto per il CANALE SUCCESSIVO'
        else:
            prompt = 'Premi il tasto per il CANALE PRECEDENTE'
        try:
            self.getControl(2).setLabel(prompt)
            self.getControl(3).setLabel(warning or
                'BACK annulla · il tasto non cambierà ancora canale in questa build')
        except Exception:
            pass

    @staticmethod
    def _event(action):
        try:
            button = int(action.getButtonCode())
        except Exception:
            button = 0
        return int(action.getId()), button

    def onAction(self, action):
        action_id, button = self._event(action)
        if action_id in _CANCEL_ACTIONS:
            self.close()
            return
        if time.time() < self._ready_at or action_id == 0 or action_id in _IGNORE_ACTIONS:
            return

        event = (action_id, button)
        logger.info('[RemoteMap] phase=%s action_id=%d button_code=%d'
                    % (self._phase, action_id, button))
        if self._phase == 'next':
            self._next = event
            self._phase = 'previous'
            self._ready_at = time.time() + 0.65
            self._show_prompt()
            return

        if event == self._next or (button and button == self._next[1]):
            self._ready_at = time.time() + 0.65
            self._show_prompt('I due comandi devono essere diversi. Premi il tasto PRECEDENTE.')
            return

        config.set_setting('live_remote_next_action', str(self._next[0]))
        config.set_setting('live_remote_next_button', str(self._next[1]))
        config.set_setting('live_remote_previous_action', str(event[0]))
        config.set_setting('live_remote_previous_button', str(event[1]))
        config.set_setting('live_remote_mapped', True)
        from platformcode import live_remote
        live_remote.save_mapping(self._next, event)
        logger.info('[RemoteMap] saved next=%s previous=%s' % (self._next, event))
        self.completed = True
        self.close()


def learn():
    dialog = RemoteKeymapDialog('RemoteKeymap.xml', config.get_runtime_path())
    dialog.doModal()
    completed = dialog.completed
    del dialog
    if completed:
        platformtools.dialog_ok(
            'Telecomando configurato',
            'Mappatura salvata. In questa build diagnostica i tasti non cambiano ancora canale.')
    else:
        platformtools.dialog_notification(
            'PrippiStream', 'Mappatura telecomando annullata', time=2500, sound=False)
